name: Unit Tests

on: push

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: latest
          cache: true

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure CMake
        run: >
          cmake -B build -S .
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build tests
        run: cmake --build build --config Release --target core_tests

      - name: Run tests
        run: ctest --test-dir build --build-config Release --output-on-failure

  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install gcc 13
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

      - name: Install vulkan sdk
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: latest
          cache: true

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure CMake
        run: >
          cmake -B build -S .
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build tests
        run: cmake --build build --config Release --target core_tests

      - name: Run tests
        run: ctest --test-dir build --build-config Release --output-on-failure
